name: Build Containers

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-core:
    name: Build Core Containers
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Build and push build container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/build.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: iowarp/core-build:latest
          cache-from: type=registry,ref=iowarp/core-build:buildcache
          cache-to: type=registry,ref=iowarp/core-build:buildcache,mode=max

      - name: Build and push deploy container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/deploy.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: iowarp/core:latest
          cache-from: type=registry,ref=iowarp/core:buildcache
          cache-to: type=registry,ref=iowarp/core:buildcache,mode=max

  build-benchmarks:
    name: Build Benchmark Containers
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: build-core
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Build and push redis benchmark
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/redis_bench.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: iowarp/redis-bench:latest

      - name: Build and push CTE benchmark
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/wrp_cte_bench.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: iowarp/cte-bench:latest
